### ISSUE TITLE
Cuid standard is deprecated.

### ISSUE THREAD

**Issue by ericelliott** [endyjasmi/cuid#9]
Due to security concerns (which also exist in database auto-increment ids, uuid/guid, and most other id standrads), the Cuid standard is now deprecated in favor of [Cuid2](https://github.com/paralleldrive/cuid2).

**Comment by endyjasmi** [comment]
Thanks for the heads up, I'll put in the deprecation notice ASAP.

**Comment by ericelliott** [comment]
It would be better if there's a Cuid2 implementation to point people to, because there are no sufficiently-secure alternative forms of id available for PHP, as far as I'm aware.
